[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "longbranch_vinaigrette_py_gitconfig"
description="App for handling git config files"
version = "1.0.0"
requires-python=">=3.10"
license = {text="MIT"}
